[2025-04-29T19:04:22.446+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-29T19:04:22.508+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:04:20.208883+00:00 [queued]>
[2025-04-29T19:04:22.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:04:20.208883+00:00 [queued]>
[2025-04-29T19:04:22.527+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-29T19:04:22.567+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_spark_pst> on 2025-04-29 19:04:20.208883+00:00
[2025-04-29T19:04:22.582+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pstspark', 'run_spark_pst', 'manual__2025-04-29T19:04:20.208883+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/pstspark.py', '--cfg-path', '/tmp/tmpf33zgjqw']
[2025-04-29T19:04:22.582+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=641) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-29T19:04:22.586+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask run_spark_pst
[2025-04-29T19:04:22.587+0000] {standard_task_runner.py:63} INFO - Started process 642 to run task
[2025-04-29T19:04:22.759+0000] {task_command.py:426} INFO - Running <TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:04:20.208883+00:00 [running]> on host 3d59bb7e8591
[2025-04-29T19:04:22.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pstspark' AIRFLOW_CTX_TASK_ID='run_spark_pst' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T19:04:20.208883+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T19:04:20.208883+00:00'
[2025-04-29T19:04:22.947+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-29T19:04:22.973+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-29T19:04:22.975+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pstspark.py", line 34, in RunSparkPst
    df = spark.read.jdbc(url=url, table="employees", properties=properties)
         ^^^^^^^^^^
AttributeError: 'Builder' object has no attribute 'read'
[2025-04-29T19:04:23.002+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pstspark, task_id=run_spark_pst, run_id=manual__2025-04-29T19:04:20.208883+00:00, execution_date=20250429T190420, start_date=20250429T190422, end_date=20250429T190423
[2025-04-29T19:04:23.028+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task run_spark_pst ('Builder' object has no attribute 'read'; 642)
[2025-04-29T19:04:23.046+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-29T19:04:23.087+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T19:04:23.099+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
