[2025-05-04T14:01:16.570+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T14:01:16.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.task_first manual__2025-05-04T14:01:14.316985+00:00 [queued]>
[2025-05-04T14:01:16.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.task_first manual__2025-05-04T14:01:14.316985+00:00 [queued]>
[2025-05-04T14:01:16.637+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-04T14:01:16.656+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_first> on 2025-05-04 14:01:14.316985+00:00
[2025-05-04T14:01:16.664+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-04T14:01:16.667+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2025-05-04T14:01:16.672+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'main', 'task_first', 'manual__2025-05-04T14:01:14.316985+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpkg772ka2']
[2025-05-04T14:01:16.680+0000] {standard_task_runner.py:91} INFO - Job 125: Subtask task_first
[2025-05-04T14:01:16.796+0000] {task_command.py:426} INFO - Running <TaskInstance: main.task_first manual__2025-05-04T14:01:14.316985+00:00 [running]> on host 3d59bb7e8591
[2025-05-04T14:01:16.937+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='task_first' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T14:01:14.316985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T14:01:14.316985+00:00'
[2025-05-04T14:01:16.938+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T14:01:23.719+0000] {logging_mixin.py:188} INFO - Файл не найден
[2025-05-04T14:01:23.720+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-04T14:01:23.721+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T14:01:23.736+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=main, task_id=task_first, run_id=manual__2025-05-04T14:01:14.316985+00:00, execution_date=20250504T140114, start_date=20250504T140116, end_date=20250504T140123
[2025-05-04T14:01:23.770+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-04T14:01:23.790+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-04T14:01:23.792+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
